### ISSUE TITLE
Seeing "Invalid time value" in the console on the example Link

### ISSUE THREAD

**Issue by imshuffling** [ShaifArfan/react-todo-app#9]
Tried adding new todo on https://wc-react-todo-app.netlify.app/

See this message in the console.

![image](https://user-images.githubusercontent.com/739061/218749502-797c164f-53f0-42ac-8ddc-179e56eb645a.png)

**Comment by jyotsna123singh** [comment]
Hello, is the issue resolved..?

**Comment by imgaf** [comment]
@ShaifArfan can you check the PR? It looks good to me now: https://deploy-preview-11--wc-react-todo-app.netlify.app/ :)
